C-HOS/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, only: [:new, :edit, :create, :update, :destroy]
  root 'categories#index'
  get 'categories/index' => 'categories#index'
  post 'categories' => 'categories#create'
  post 'categories/:id/edit' => 'categories#edit'
  post 'categories/:id' => 'posts#index'
  post 'categories/:id/destroy' => 'categories#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: [:new, :edit, :create, :update, :destroy]
  get 'posts' => 'posts#index'
  get 'categories/:id' => 'posts#index'
  get 'categories/:id/new' => 'posts#new'
  post 'posts' => 'posts#create'
  get 'posts/:id' => 'posts#show'
  post 'posts/:id/destroy' => 'posts#destroy'
end

C-HOS/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

C-HOS/app/models/category.rb
class Category < ApplicationRecord
    has_many :post_categories
    has_many :posts, through: :post_categories
end

C-HOS/app/models/comment.rb
class Comment < ApplicationRecord
end

C-HOS/app/models/follow.rb
class Follow < ApplicationRecord
end

C-HOS/app/models/like.rb
class Like < ApplicationRecord
end

C-HOS/app/models/notification.rb
class Notification < ApplicationRecord
end

C-HOS/app/models/post.rb
class Post < ApplicationRecord
    has_many :post_categories
    has_many :categories, through: :post_categories
    mount_uploader :img, ImageUploader
end

C-HOS/app/models/post_caregory.rb
class PostCaregory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

C-HOS/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_name, presence: true
end

C-HOS/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :profile])
  end
end

C-HOS/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @category = Category.new
        @categories = Category.all
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to categories_index_path
        else
            @categories = Category.all
            render 'index'
        end
    end
    
    def edit
        @category = Category.find(params[:id])
    end
    
    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to categories_index_path
    end
    
    def update
        @category = Category.find(params[:id])
        @category.update(category_params)
        redirect_to categories_index_path
    end

private
    def category_params
        params.require(:category).permit(:category_name)
    end
end

C-HOS/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

C-HOS/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.where(category_id:params[:id])
        @category = Category.find(params[:id])
    end
    def new
        @post = Post.new
    end
    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to controller: 'posts', action: 'show', id: @post.id
        else
            redirect_to :action => "new"
        end
    end
    def show
        @post = Post.find(params[:id])
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to controller: 'categories', action: 'index'
    end
    def edit
        @editpost = Post.find(params[:id])
    end
    def update
        @editpost = Post.find(params[:id])
        @editpost.update(post_params)
        redirect_to controller: 'posts', action: 'show', id: @editpost.id
    end
    private
    def post_params
        params.require(:post).permit(:title, :overview, :img, :category_id)
    end
end

C-HOS/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

C-HOS/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

C-HOS/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

C-HOS/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

C-HOS/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def search
        if params[:search_word].present?
            @users = User.where('user_name LIKE ?', "%#{params[:search_word]}%")
        else
            @users=User.none
        end
    end
end

C-HOS/app/helpers/application_helper.rb
module ApplicationHelper
end

C-HOS/app/helpers/categories_helper.rb
module CategoriesHelper
end

C-HOS/app/helpers/comments_helper.rb
module CommentsHelper
end

C-HOS/app/helpers/posts_helper.rb
module PostsHelper
end

C-HOS/app/helpers/users_helper.rb
module UsersHelper
end

C-HOS/app/views/categories/edit.html.erb
</br></br>
<%= form_with model: @category, url: category_path do |f| %>
    <div>
        <%= f.label :カテゴリ名変更 %></br>
        <%= f.text_field :category_name, :placeholder =>"#{@category.category_name}",  class:"category-form" %>
        <%= f.submit "Edit name", class: "update"  %>
    </div>
<% end %>

C-HOS/app/views/categories/index.html.erb
<div class="wrop">
    <%= form_with model: @category, local: true do |f| %>
            <%= f.label :New_category_name %></br>
            <%= f.text_field :category_name, class:"category-form" %>
            <%= f.submit "Add new category", class: "update" %>
    <% end %>
    <% @categories.each do |category| %>
        <div class="content">
        <table>
        <tbody>
            <td>
                <%= category.category_name %>
            </td>
            <td>
                <%= button_to("view", "/categories/#{category.id}",{class:"show-btn"}) %>
            </td>
            <td>
                <%= button_to("edit","/categories/#{category.id}/edit",{method: "category",class:"edit-btn"}) %>
            </td>
            <td>
                <%= button_to("delete","/categories/#{category.id}/destroy",{method: "category",class:"destroy-btn"}) %>
            </td>
        </tbody>
        </table>
        </div>
    <% end %>

C-HOS/app/views/posts/edit.html.erb
<h1>投稿編集</h1>
<%= form_with model: @editpost, url: post_path do |f| %>
    <div class="field">
        <%= f.label :カテゴリ %><br/>
        <%= f.collection_select :category_id, Category.all, :id, :category_name %>
    </div>
    <div class="field">
        <%= f.label :タイトル %><br>
        <%= f.text_field :title, :placeholder =>"#{@editpost.title}", :size => 100 %>
    </div>
    <div class="field">
        <%= f.label :本文 %><br>
        <%= f.text_area :overview, :placeholder =>"#{@editpost.overview}", size: "90x10" %>
    </div>
    <%= f.label :画像 %><br>
    <%= f.file_field :img,:placeholder =>"#{@editpost.img}", class: "image" %><br>
    <%= f.submit "保存" %>
<% end %>
<%= link_to("戻る", "/posts/#{@editpost.id}") %>

<%= link_to '投稿一覧へ', :controller => "posts", :action => "index" %>

C-HOS/app/views/posts/index.html.erb
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
    <span>
    <%= @category.category_name %>
    _
    <%= link_to post.title, "/posts/#{post.id}" %></span>
    </br>
    ------------------------------------------------------------
    </br>
<% end %>
            

<%= link_to '新規投稿', :controller => "posts", :action => "new" %></br>
<%= link_to 'カテゴリ管理画面へ', :controller => "categories", :action => "index" %>

C-HOS/app/views/posts/new.html.erb
<div class="col-sm-12">
    <h2 class="text-center">新規投稿</h2>
    <%= form_with model: @post, local: true do |f| %>
        <div class="form_input">
        <%= f.label :カテゴリ %><br/>
        <%= f.collection_select :category_id, Category.all, :id, :category_name %>
        </div>
        <div class="form_input">
            <%= f.label :タイトル %><br/>
            <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form_input">
            <%= f.label :本文 %><br/>
            <%= f.text_area :overview, class: "form-control" %>
        </div>
        <div class="form_input">
            <%= f.label :画像 %><br/>
            <%= f.file_field :img, class: "image" %>
        </div>

        <div class="form_action row"><br/>
        <%= f.submit "投稿する", class: "btn col-sm-12 submit_btn" %>
        </div>
    <% end %>

    <%= link_to '戻る', :controller => "posts", :action => "index" %>
</div>

C-HOS/app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>本文</h2>
<p><%= @post.overview %></p>
<h2>画像</h2>
<% if @post.img? %>
    <p><%= image_tag @post.img.url %></p>
<% else %>
    <p>Noimage</p>
<% end %>
<%= link_to("編集", "/posts/#{@post.id}/edit") %><br>
<%= button_to("削除","/posts/#{@post.id}/destroy",{method: "post"}) %>
<%= link_to '投稿一覧へ', "/categories/#{@post.category_id}" %></span>